name: spinner_input_plus
description: A Spinner Input for flutter. Almost like html5 input-spinners, it has up/down buttons and also explicit value edit capability.
version: 0.0.4
homepage: https://github.com/CsabaConsulting/spinner_input_plus

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  intl: ^0.20.2
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^7.2.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
